runtime: python310  # Python runtime, update as needed (use a version that suits your project)

handlers:
  - url: /static
    static_dir: static
  - url: /
    static_files: index.html
    upload: index.html
  - url: /.* 
    static_files: dist/\1
    upload: dist/.*

